"""
Django settings for gym project.
Generated by 'django-admin startproject' using Django 3.2.25.
"""

import os
from pathlib import Path

# Load environment variables
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    print("Warning: python-dotenv not installed, using system environment variables")

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent

# ========================
# Security & Core Settings
# ========================
SECRET_KEY = os.environ['SECRET_KEY']  # From .env
DEBUG = True
ALLOWED_HOSTS = []

# ============
# Applications
# ============
INSTALLED_APPS = [
    # Django Core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    # Third-party
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    
    # Local Apps
    'main',
    'gym_auth.apps.GymAuthConfig',
]

# ==============
# Authentication
# ==============
AUTH_USER_MODEL = 'gym_auth.CustomUser'
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Allauth Config
SITE_ID = 1
LOGIN_REDIRECT_URL = '/schedule/'  # After successful login
LOGOUT_REDIRECT_URL = '/'          # After logout
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Disable email verification
ACCOUNT_LOGOUT_ON_GET = True        # Simplify logout

# ============
# Middleware
# ============
MIDDLEWARE = [
    # Security & core
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    # Common
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    
    # Auth
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    
    # Messages
    'django.contrib.messages.middleware.MessageMiddleware',
    
    # Security
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # Allauth (NEW)
    'allauth.account.middleware.AccountMiddleware',
]

# ========
# URLs & WSGI
# ========
ROOT_URLCONF = 'gym.urls'
WSGI_APPLICATION = 'gym.wsgi.application'

# ========
# Database
# ========
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ===============
# Password Validation
# ===============
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# =============
# Internationalization
# =============
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# =============
# Static & Media Files
# =============
STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# =============
# Templates
# =============
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# =============
# Misc
# =============
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# =============
# Production Overrides (When DEBUG=False)
# =============
if not DEBUG:
    ALLOWED_HOSTS = ['yourdomain.com']
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True