# Generated by Django 3.2.25 on 2025-05-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_auth', '0002_auto_20250528_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
